---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../.yamllint
platforms:
  - name: instance
    image: ubuntu:16.04  # TODO parametrize
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbooks/playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../resources/tests
  lint:
    name: flake8
