---
- name: Ensure 'aws_clients_provisioner' host exists
  gather_facts: false
  hosts: localhost
  tasks:
    - include_tasks: tasks/ensure_provisioner.yml
      vars:
        provisioner_host: aws_clients_provisioner

- name: Provision hosts for clients
  gather_facts: false
  hosts: aws_clients_provisioner
  roles:
    - role: aws_manage
      vars:
        aws_group_name: clients
...
