---
- name: Ensure 'aws_nodes_provisioner' host exists
  gather_facts: false
  hosts: localhost
  tasks:
    - include_tasks: tasks/ensure_provisioner.yml
      vars:
        provisioner_host: aws_nodes_provisioner

- name: Provision hosts for nodes
  gather_facts: false
  hosts: aws_nodes_provisioner
  roles:
    - role: aws_manage
      vars:
        aws_group_name: nodes
...
