---
- name: Check that required variables are specified
  assert:
    that:
      - lookup('vars', item, default='')
    msg: "{{ lookup('vars', item, default='undefined')|string }}"
  loop:
    - aws_ec2_type
    - aws_ami_id
    - aws_tag_namespace
    - aws_tag_role
    - group_name
    - inventory_dir
    - aws_keyname
    - aws_sgroup
    - instance_count
    - aws_regions

- name: Pre-Up
  include_tasks: "{{ role_path }}/tasks/pre_up.yml"
  when: instance_count > 0

- name: Manage instances
  stateful_set:
    regions: "{{ aws_regions }}"
    namespace: "{{ aws_tag_namespace }}"
    role: "{{ aws_tag_role }}"
    key_name: "{{ aws_keyname }}"
    group: "{{ aws_sgroup }}"
    instance_type: "{{ aws_ec2_type }}"
    instance_count: "{{ instance_count }}"
  register: ec2

- name: Post-Up
  include_tasks: "{{ role_path }}/tasks/post_up.yml"
  when: instance_count > 0

- name: Post-Down
  include_tasks: "{{ role_path }}/tasks/post_down.yml"
  when: instance_count == 0
