---
- name: Pre-Checks - check variables
  import_tasks: "pre_checks.yml"

- name: Set ssh_dir_name variable
  set_fact:
    ssh_dir_name: .ssh

- name: Set ssh_dir variable
  set_fact:
    ssh_dir: "{{ aws_inventory_dir }}/{{ ssh_dir_name }}"

- name: Pre-Up
  import_tasks: "pre_up.yml"
  when: instance_count > 0

- name: Manage instances
  stateful_set:
    regions: "{{ aws_regions }}"
    project: "{{ aws_tag_project }}"
    namespace: "{{ aws_tag_namespace }}"
    role: "{{ aws_tag_role }}"
    add_tags: "{{ aws_add_tags }}"
    key_name: "{{ aws_keyname }}"
    group: "{{ aws_sgroup }}"
    instance_type: "{{ aws_ec2_type }}"
    instance_count: "{{ instance_count }}"
  register: ec2

- name: Post-Up
  import_tasks: "post_up.yml"
  when: instance_count > 0

- name: Post-Down
  import_tasks: "post_down.yml"
  when: instance_count == 0
