---
- name: Create ssh config
  template:
    src: ssh_config.j2
    dest: "{{ ssh_dir }}/ssh_config"

- name: Create inventory file for AWS hosts
  template:
    src: hosts.j2
    dest: "{{ aws_inventory_file }}"
