---
- name: Create/Update ssh config
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config }}"

- name: Create/Update known_hosts file
  import_tasks: "set_known_hosts.yml"
  vars:
    alive: "{{ aws_ec2hosts.alive|map(attribute='public_ip')|list }}"
    terminated: "{{ aws_ec2hosts.terminated|map(attribute='public_ip')|list }}"

- name: Create/Update inventory file for AWS hosts
  vars:
    ssh_private_key: "{% raw %}{{ inventory_dir }}{% endraw %}/{{ ssh_dir_name }}/{{ ssh_key_name }}"
    known_hosts_file: "{% raw %}{{ inventory_dir }}{% endraw %}/{{ ssh_dir_name }}/{{ ssh_known_hosts_name }}"
  template:
    src: hosts.j2
    dest: "{{ aws_inventory_file }}"
