---
- name: Check that required variables are specified
  assert:
    that:
      - lookup('vars', item, default='')
    msg: "{{ lookup('vars', item, default='undefined')|string }}"
  loop:
    - perf_scripts_build_dir
    - perf_scripts_ver
    - perf_scripts_pool_genesis_txns_name
    - perf_scripts_pool_genesis_txns_path_local
    - perf_scripts_pool_genesis_txns_path_remote

# TODO rename of split
- name: Install pip and other required packages
  apt:
    name:
      - python3-pip
      - python-setuptools # neeeded for ansible's pip (TODO actually depends on python used by ansible)
      - virtualenv
      - git
      - libsodium18 # TODO might depends on target platform package distributions
      - vim # TODO think about other useful tools and move to client_install
    update_cache: true
  become: true

- name: Install virtualenv globally
  pip:
    name:
      - virtualenv
    executable: pip3
  become: true

- name: Install performance scripts from the VCS
  pip:
    name: "git+https://github.com/hyperledger/indy-node.git@{{ perf_scripts_ver }}#egg=subdir&subdirectory=scripts/performance"
    virtualenv: "$HOME/{{ perf_scripts_venv_name }}"  # $HOME as a workaround
    virtualenv_python: python3

- name: Configuration tasks
  include_tasks: configure.yml
  when: perf_scripts_configuration
