---
# AWS primary parameters
aws_type: t2.micro
aws_image: ami-027583e616ca104df

# Tags
tag_namespace: test-default
tag_role: node

# Derivative parameters
group_name: "{{ tag_role }}s"
inventory_dir: "{{ tag_namespace }}_{{ group_name }}"
aws_keyname: "{{ tag_namespace }}-{{ group_name }}"
aws_group: "{{ tag_namespace }}-{{ group_name }}"
instance_count: 4

# List of all potential regions to use
aws_regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
