---
# AWS primary parameters
aws_ec2_type: t2.micro

# Tags
aws_tag_project: PoolAutomation
aws_tag_role: default

# List of all potential regions to use
aws_regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

instance_count: 4

# Derivative parameters
group_name: "{{ aws_tag_role }}s"

aws_tag_namespace: "{{ inventory_dir | default('test', true) | basename }}"
aws_inventory_dir: "{{ inventory_dir | default(aws_tag_namespace ~ '_' ~ group_name) }}"
aws_inventory_file: "{{ aws_inventory_dir }}/hosts"
aws_keyname: "{{ aws_tag_project }}-{{ aws_tag_namespace }}-{{ group_name }}"
aws_sgroup: "{{ aws_tag_project }}-{{ aws_tag_namespace }}-{{ group_name }}"
